FROM ubuntu:17.04
RUN apt update && apt -y upgrade && apt install -y software-properties-common curl locales systemd
RUN echo "deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list
RUN curl https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub | apt-key add -

RUN sed -i'' "s/\# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen && locale-gen
RUN apt update && apt -y install salt-minion
RUN mkdir -p /srv/salt
COPY salt/srv/salt /srv/salt
COPY salt/etc/salt/minion.docker /etc/salt/minion
RUN salt-call --local state.sls deploy saltenv=base
ENV PYTHONPATH=/app/pycharm-debug-py3k.egg:/app/web:/app/web/web
ENV DJANGO_SETTINGS_MODULE=settings.development
VOLUME /app
CMD ["/lib/systemd/systemd"]

